# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: cd ~/repo/backend
      - run: ls ~/repo/backend
      - run: ls ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/repo/backend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install
          working_directory: ~/repo/backend

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/repo/backend/package.json" }}

      - run:
          name: Test
          command: yarn test
          working_directory: ~/repo/backend
      - run:
          name: Generate code coverage
          command: "./node_modules/.bin/nyc report --reporter=text-lcov"
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
