const initialSearchActionTypes = {
  FETCH_INITIAL_SEARCH_RESULTS_REQUEST: 'FETCH_INITIAL_SEARCH_RESULTS_REQUEST',
  FETCH_INITIAL_SEARCH_RESULTS_REQUEST_SUCCESS: 'FETCH_INITIAL_SEARCH_RESULTS_REQUEST_SUCCESS',
  FETCH_INITIAL_SEARCH_RESULTS_REQUEST_FAIL: 'FETCH_INITIAL_SEARCH_RESULTS_REQUEST_FAIL',
};

export default initialSearchActionTypes;
