const searchActionTypes = {
  FETCH_SEARCH_RESULTS_REQUEST: 'FETCH_SEARCH_RESULTS_REQUEST',
  FETCH_SEARCH_RESULTS_REQUEST_SUCCESS: 'FETCH_SEARCH_RESULTS_REQUEST_SUCCESS',
  FETCH_SEARCH_RESULTS_REQUEST_FAIL: 'FETCH_SEARCH_RESULTS_REQUEST_FAIL',
};

export default searchActionTypes;
